apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mose
  name: mose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mose
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mose
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
